### ISSUE TITLE
Make an Option to Disable Idle - GameUtil

### ISSUE THREAD

**Issue by he3als** [Atlas-OS/Atlas-Utilities#3]
I think that it would be useful to have a toggle for disabling idle in GameUtil, so whilst you are gaming, your CPU is not changing C-states.

**Comment by he3als** [comment]
Also, I am going to learn Rust and I am planning on contributing here. 👍

**Comment by Zusier** [comment]
Check the screenshot on the README.md. Idle is an option

**Comment by he3als** [comment]
Oh sorry, nice. I did not see that somehow. 😅

**Comment by Zusier** [comment]
> Also, I am going to learn Rust and I am planning on contributing here. 👍

Awesome, if you have any questions I can probably help in DMs :)
