### ISSUE TITLE
Timer Resolution Doesn't Work on 2004+ - GameUtil

### ISSUE THREAD

**Issue by he3als** [Atlas-OS/Atlas-Utilities#4]
The timer resolution feature will not work for Windows 10 2004+, so maybe the option should not appear if version is 2004+ or above. A note about it could also function fine, or maybe the timer resolution feature could have a toggle and automatically be toggled off.

**Comment by Zusier** [comment]
I'm aware. Planning on adding tooltips but it seems that NWG (the gui lib) doesnt have a tooltip option, or are separate objects

I'll look into it

**Comment by Zusier** [comment]
Done :)
