### ISSUE TITLE
Game security violation detected (#00000001) in apex legends

### ISSUE THREAD

**Issue by Natram1zh** [Atlas-OS/Atlas-Utilities#5]
![Capture](https://user-images.githubusercontent.com/83518657/159590962-23ffd0a9-d2c3-4112-8dac-ecbfe5b3fca5.PNG)
This happens when i kill dwm then after 1 or 2 mins this message pop out : (

Using 1709

**Comment by Zusier** [comment]
Did you clean memory?

**Comment by Natram1zh** [comment]
No

**Comment by Zusier** [comment]
Did you launch gameutil before the game launched? do the opposite or vice versa

**Comment by Natram1zh** [comment]
I will try it now, i launched game first and then opened gameutili

**Comment by Natram1zh** [comment]
Both gives same result. 1 or 2 mins same message pops out. may be easy anti-cheat is broken : ( or it detects your program as a cheat.

**Comment by Zusier** [comment]
Try just explorer, and don't launch with NSudo. Every other person that tried the solution with apex or any EAC game said it worked.

**Comment by Natram1zh** [comment]
i didn't launch with NSudo but it is ok. I want to kill dwm in 1709 but now i am in 20h2 so no need. sry i can't try it again (apex is worst in banning players so i can't take risk and support is so bad) anyways thx for fast reply.

**Comment by Natram1zh** [comment]
I got the same error in 1803 atlas os while killing dwm but no problem in killing explorer ¯\_(ツ)_/¯

**Comment by Zusier** [comment]
Yes.. it wouldn't change across windows versions.

**Comment by Natram1zh** [comment]
I know but for some reason I checked it again and opened the issue. You found out any fix for it?

**Comment by Zusier** [comment]
No, EAC probably doesn't allow killing DWM

**Comment by Natram1zh** [comment]
What I used to kill dwm with process explorer in apex season 7 or 8 (1.2 years before). Anyways for helping.

**Comment by Natram1zh** [comment]
Apex is getting dx12 support also steam version doesn't ship with that exe. So may because of this killing dwm while playing apex is not possible anymore, also fse is borken because of this update. 
![unknown](https://user-images.githubusercontent.com/83518657/164178885-05d79de2-0d20-4559-9a57-162c797ee92d.png)


And I got this message from calypto server https://discord.com/channels/525905837978288130/525905837978288132/960613942189764668
