### ISSUE TITLE
Add me to the thing I want to make small updater that dose not run in the background when go to settings go to updates and then you click find update and it will download it from atlas OS GitHub so they can get recoded version

### ISSUE THREAD

**Issue by frayray909090** [Atlas-OS/Atlas-Utilities#6]
Add [frayray909090](https://github.com/) to the group please I’ll do some coding

**Comment by Zusier** [comment]
Updater for atlas? If so I’m not interested unless it somehow updates component changes.

**Comment by frayray909090** [comment]
Oh I will make custom updated so it don’t download from microstructure it downloads it from here if som code is different it will download the parts but it will not install settings because you change them
