### ISSUE TITLE
Support arguments for command line launch of gameutil

### ISSUE THREAD

**Issue by MattPonton** [Atlas-OS/Atlas-Utilities#9]
Feature Request:

Would it be possible to add command line arguments to `gameutil` and `gameutil-rs` so that I can have it auto start on launch with given settings? Something like the following for setting the TIMERRES, KILL_DWM to true, DISABLE_IDLE to true, and starting immediately with those settings:

`gameutil -autostart 0 -dwm -idle`

Use case:
I'd like to have the program launch at startup without having to select anything as I may not have my mouse or keyboard attached to the system.

**Comment by Zusier** [comment]
Yes, I'll work on that

**Comment by Zusier** [comment]
CLI arguments have been added. Autostart has not been implemented just yet because of a complexity in the GUI, I'll see what I can do about it though. Thanks for the suggestion!

**Comment by MattPonton** [comment]
Thanks @Zusier ! I've attempted various commands with gameutil-rs and I can't seem to boot it with the Kill Explorer boolean set to false via command line. If I omit --kill-explorer it comes up true. if I include --kill-explorer it also comes up true.
